### ISSUE TITLE
Biopython dependency conflict in environment.yml and requirements.txt

### ISSUE THREAD

**Issue by darnells** [AstraZeneca/DiffAbXL#5]
I am trying to set up an environment to work with DiffAbXL. The `modelling-dev` conda environment uses python 3.7. The pip requirements list biopython==1.84; however, this version only supports python 3.9 or later. Is a newer version of python required or does one need to use two python interpreters? Could recommended installation instructions be added to README.md?

Commands:
```
git clone https://github.com/AstraZeneca/DiffAbXL.git
~/miniforge3/bin/conda env create --no-default-packages --file DiffAbXL/environment.yml
~/miniforge3/envs/modelling-dev/bin/pip3 install --no-cache-dir --requirement DiffAbXL/requirements.txt
```

Output:
```
ERROR: Ignored the following versions that require a different python version: 1.82 Requires-Python >=3.8; 1.83 Requires-Python >=3.8; 1.84 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement biopython==1.84 (from versions: 1.0a3, 1.0a4, 1.10, 1.20, 1.21, 1.22, 1.23, 1.24, 1.30, 1.40b0, 1.41, 1.42, 1.43, 1.44, 1.45, 1.46, 1.47, 1.48, 1.49b0, 1.49, 1.50b0, 1.50, 1.51b0, 1.51, 1.52, 1.53, 1.54b0, 1.54, 1.55b0, 1.55, 1.56, 1.57, 1.58, 1.59, 1
.60, 1.61, 1.62b0, 1.62, 1.63b0, 1.63, 1.64, 1.65, 1.66, 1.67, 1.68, 1.69, 1.70, 1.71, 1.72, 1.73, 1.74, 1.75, 1.76, 1.77, 1.78, 1.79, 1.80, 1.81)
ERROR: No matching distribution found for biopython==1.84
```

**Comment by darnells** [comment]
Additionally, pillow==9.6.0 is not in PyPI. The surrounding versions are 9.5.0 and 10.0.0.

**Comment by talipucar** [comment]
Hi @darnells ,

1. Regarding the Python version, I'm currently using Python 3.11.8 and will update the environment.yml accordingly.
2. For the Pillow library, please use version 10.2.0. My current environment includes many packages that are not necessary for this project. To minimise the requirements, I’ve removed most of the unnecessary packages, though I may have unintentionally removed some important ones. I will update the README with detailed setup instructions when I can find the time.

I hope this helps. I will close this issue, but If you encounter any further issues with dependencies, feel free to reopen the ticket.
